/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.InicioController;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Rollán García
 */
public class Inicio extends javax.swing.JFrame {

  /**
   * Creates new form Inicio
   */
  private final InicioController controller = new InicioController();

  public Inicio() {
    FlatLightOwlIJTheme.setup();
    initComponents();
    actualizarEstilos();
  }

  public void insertarCliente(String nombre, String nif, String email, String telefono) {
    controller.insertarCliente(nombre, nif, email, telefono);
  }

  public void borrarClientes() {
    controller.borrarClientes();
  }

  public void borrarPedidos() {
    controller.borrarPedidos();
  }

  public void borrarDetallePedidos() {
    controller.borrarDetallePedidos();
  }

  public void borrarTablaCliente() {
    controller.borrarTablaCliente();
  }

  public void borrarTablaPedidos() {
    controller.borrarTablaPedidos();
  }

  public void borrarTablaDetallePedido() {
    controller.borrarTablaDetallePedido();
  }

  public void crearTablaCliente() {
    controller.crearTablaCliente();
  }

  public void crearTablaPedido() {
    controller.crearTablaPedido();
  }

  public void crearTablaDetallePedido() {
    controller.crearTablaDetallePedido();
  }

  public void actualizarEstilos() {

    NombreUsu.putClientProperty("JTextField.placeholderText", "Nombre de usuario");
    Nifusu.putClientProperty("JTextField.placeholderText", "NIF");
    TelUsu.putClientProperty("JTextField.placeholderText", "Teléfono");
    CorreoUsu.putClientProperty("JTextField.placeholderText", "TuCorreo@Gmail.com");

    Nifusu.putClientProperty("FlatLaf.style", "arc:10");
    TelUsu.putClientProperty("FlatLaf.style", "arc:10");
    CorreoUsu.putClientProperty("FlatLaf.style", "arc:10");
    NombreUsu.putClientProperty("FlatLaf.style", "arc:10");

    Nifusu.putClientProperty("JTextField.leadingIcon", new FlatSVGIcon("Imagenes/NifIcon.svg"));
    NombreUsu.putClientProperty("JTextField.leadingIcon", new FlatSVGIcon("Imagenes/PerfilIcon.svg"));
    CorreoUsu.putClientProperty("JTextField.leadingIcon", new FlatSVGIcon("Imagenes/correoIcon.svg"));
    TelUsu.putClientProperty("JTextField.leadingIcon", new FlatSVGIcon("Imagenes/iphoneIcon.svg"));

  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel5 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    CerrarSesionLb = new javax.swing.JLabel();
    EmpezarPedirLb = new javax.swing.JLabel();
    NombreUsu = new javax.swing.JTextField();
    Nifusu = new javax.swing.JTextField();
    CorreoUsu = new javax.swing.JTextField();
    TelUsu = new javax.swing.JTextField();
    FondoLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPngPequeño.png"))); // NOI18N
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 26, 40, 40));

    jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Sabores Digitales");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

    jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("DAM");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

    jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("¡CONOCE ");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 800, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(237, 110, 132));
    jLabel4.setText("SABORES ÚNICOS!");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 860, -1, -1));

    jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 78)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("BIENVENIDO");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

    CerrarSesionLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarSesion.png"))); // NOI18N
    CerrarSesionLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    CerrarSesionLb.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        CerrarSesionLbMouseClicked(evt);
      }
    });
    getContentPane().add(CerrarSesionLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 713, 460, 62));

    EmpezarPedirLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmpezarPedir.png"))); // NOI18N
    EmpezarPedirLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    EmpezarPedirLb.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        EmpezarPedirLbMouseClicked(evt);
      }
    });
    getContentPane().add(EmpezarPedirLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 619, 460, 62));

    NombreUsu.setBackground(new java.awt.Color(58, 23, 23));
    getContentPane().add(NombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 269, 460, 68));

    Nifusu.setBackground(new java.awt.Color(58, 23, 23));
    getContentPane().add(Nifusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 352, 460, 68));

    CorreoUsu.setBackground(new java.awt.Color(58, 23, 23));
    getContentPane().add(CorreoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 435, 460, 68));

    TelUsu.setBackground(new java.awt.Color(58, 23, 23));
    getContentPane().add(TelUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 519, 460, 68));

    FondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.png"))); // NOI18N
    getContentPane().add(FondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1429, 928));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void EmpezarPedirLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpezarPedirLbMouseClicked
    // Obtener los valores de los campos de texto
    String nombre = NombreUsu.getText();
    String nif = Nifusu.getText();
    String email = CorreoUsu.getText();
    String telefono = TelUsu.getText();

    // Validar que los campos no estén vacíos
    if (nombre.isEmpty() || nif.isEmpty() || email.isEmpty() || telefono.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else {
      // Validar formato de NIF
      if (!nif.matches("[0-9]{8}[A-Za-z]")) {
        JOptionPane.showMessageDialog(this, "El NIF no es válido. Debe tener 8 números y una letra al final.", "Advertencia", JOptionPane.WARNING_MESSAGE);
      } // Validar formato de correo electrónico
      else if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "El correo electrónico no es válido. Por favor ingresa un correo correcto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
      } // Validar formato de teléfono
      else if (!telefono.matches("\\d{9}")) {
        JOptionPane.showMessageDialog(this, "El teléfono no es válido. Debe tener 9 dígitos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
      } else {
        Modelo.DatosUsuario.setNif(nif);
        Modelo.DatosUsuario.setCorreo(email);
        // Llamar al método para insertar el cliente en la base de datos
        insertarCliente(nombre, nif, email, telefono);

        // Limpiar los campos después de guardar
        NombreUsu.setText("");
        Nifusu.setText("");
        CorreoUsu.setText("");
        TelUsu.setText("");
        this.dispose();

        // Crea una nueva instancia de la clase Entrantes y la hace visible
        Entrantes ventanaEntrantes = new Entrantes();
        ventanaEntrantes.setVisible(true);
      }
    }
  }//GEN-LAST:event_EmpezarPedirLbMouseClicked

  private void CerrarSesionLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionLbMouseClicked
    int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres salir?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (respuesta == JOptionPane.YES_OPTION) {
      borrarDetallePedidos();
      borrarPedidos();
      borrarClientes();
      borrarTablaDetallePedido();
      borrarTablaPedidos();
      borrarTablaCliente();
      crearTablaCliente();
      crearTablaPedido();
      crearTablaDetallePedido();
      System.exit(0);    // TODO add your handling code here:
  }//GEN-LAST:event_CerrarSesionLbMouseClicked
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Inicio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel CerrarSesionLb;
  private javax.swing.JTextField CorreoUsu;
  private javax.swing.JLabel EmpezarPedirLb;
  private javax.swing.JLabel FondoLabel;
  private javax.swing.JTextField Nifusu;
  private javax.swing.JTextField NombreUsu;
  private javax.swing.JTextField TelUsu;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  // End of variables declaration//GEN-END:variables
}
