/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.PlatosController;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme;
import java.sql.Connection;
import javax.swing.JScrollPane;
import lombok.Getter;

/**
 *
 * @author Pedro Rollán García
 */
@Getter
public class Platos extends javax.swing.JFrame {

  private Connection connection;
  private String nifUsuario;

  public Platos() {
    FlatLightOwlIJTheme.setup();
    initComponents();
    this.nifUsuario = Modelo.DatosUsuario.getNif();
    PlatosController PlatosController = new PlatosController();
    PlatosController.cargarPlatos(MenuPlatos, nifUsuario);
  }

  public JScrollPane getScrollPanePlatos() {
    return MenuPlatos;
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFrame1 = new javax.swing.JFrame();
    MenuLateral1 = new javax.swing.JPanel();
    MenuSuperior1 = new javax.swing.JPanel();
    MenuEntrantes1 = new javax.swing.JScrollPane();
    MenuPlatos = new javax.swing.JScrollPane();

    jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    MenuLateral1.setBackground(new java.awt.Color(204, 204, 204));

    javax.swing.GroupLayout MenuLateral1Layout = new javax.swing.GroupLayout(MenuLateral1);
    MenuLateral1.setLayout(MenuLateral1Layout);
    MenuLateral1Layout.setHorizontalGroup(
      MenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 256, Short.MAX_VALUE)
    );
    MenuLateral1Layout.setVerticalGroup(
      MenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 863, Short.MAX_VALUE)
    );

    jFrame1.getContentPane().add(MenuLateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 256, 863));

    MenuSuperior1.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout MenuSuperior1Layout = new javax.swing.GroupLayout(MenuSuperior1);
    MenuSuperior1.setLayout(MenuSuperior1Layout);
    MenuSuperior1Layout.setHorizontalGroup(
      MenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1144, Short.MAX_VALUE)
    );
    MenuSuperior1Layout.setVerticalGroup(
      MenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 66, Short.MAX_VALUE)
    );

    jFrame1.getContentPane().add(MenuSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 0, 1144, 66));

    MenuEntrantes1.setBackground(new java.awt.Color(102, 102, 102));
    jFrame1.getContentPane().add(MenuEntrantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 66, 1144, 797));

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    MenuPlatos.setBackground(new java.awt.Color(102, 102, 102));
    getContentPane().add(MenuPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1144, 797));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;

        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Platos.class
        .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Platos.class
        .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Platos.class
        .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Platos.class
        .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Platos().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane MenuEntrantes1;
  private javax.swing.JPanel MenuLateral1;
  private javax.swing.JScrollPane MenuPlatos;
  private javax.swing.JPanel MenuSuperior1;
  private javax.swing.JFrame jFrame1;
  // End of variables declaration//GEN-END:variables
}
